### ISSUE TITLE
Understanding the raw data

### ISSUE THREAD

**Issue by shivangibithel** [naver-ai/eccv-caption#1]
Hi @SanghyukChun 

This is an amazing work on correcting some of the MS-COCO queries. I am also working in the similar domain of building VL models and loved the idea of evaluating the upcoming models on this dataset. I have some confusion while using the dataset. In the paper, It is mentioned that you sub-sampled the mscoco test set of 5000 images to 1261 images and 25000 text to 1331 text. So, Is this the only final dataset which is ECCV dataset - 1261 images and 1331 text ? Or these are just the queries and retrieval set for image-text retrieval will be different? I saw the mturk_parsed.csv file, It has more number of unique images and text in it, which got me into the confusion about a different retrieval set/ 

Can you please clarify this? 

Thanks in advance.

**Comment by SanghyukChun** [comment]
Roughly speaking, there are two different ECCV Caption test sets for image-to-text retrieval and text-to-image retrieval:
- Image-to-text: 1,261 images are queries (subsampled from 5,000 images) and the gallery set is 25,000 captions (the whole captions)
- Text-to-image: 1,331 captions are queries (subsampled from 25,000 captions) and the gallery set is 5,000 images (the whole images)

Therefore, the ECCV Caption test set and the COCO Caption test set have the same gallery set; it means that the ECCV Caption R@K is compatible with COCO **_5K_** R@K directly because the gallery set is the same (but ECCV Caption has more positives than COCO Caption).

As wroten in the paper, it was too expensive to collect all possible image-to-caption relationships. Hence, when we collect the human-verified image-to-caption relations, we first filtered out image-to-caption pairs based on SOTA retrieval models, and then subsample **query items**.

The MTurk csv contains the whole image-to-text justifications. Because the annotators have no idea about where the items come from (e.g., from the image-to-caption retrieval subset or the caption-to-image retrieval subset). After collecting the responses, I applied post-processing based on the subsampled query ids.

**Comment by shivangibithel** [comment]
Thank you @SanghyukChun  for the early response and clarification. One more thing that I would like to clarify is, what is the ranking field and annotation here in the mturk csv? as both have a number in a scale of 1-4 

Fom what I understood 
Ranking - ? maybe ranking given by these models 
score - Image text matching score given by MITL models
Cid - Caption ID of MS-COCO dateset
IID - Image ID of MS-COCO Dataset
Annotation - on a scale of 4 (Yes, partially yes, mostly no, No)
shortcomings - reasons for saying partially yes and mostly No

![MicrosoftTeams-image](https://user-images.githubusercontent.com/19774925/216806497-792143c2-cce2-410b-90e3-727ff2fd9b88.png)

**Comment by shivangibithel** [comment]
In the paper, there is an experiment where mAP@R and Recall merics is compared by giving different rankings to the humans. I am wondering, if you have the graded scale annotation on a scale of 4, did you also try to compute the nDCG metric and what was your findings if any?
As it is mentioned in the paper that some annotations might be noisy as you combined Yes and Partial Yes to form the positive set.

**Comment by SanghyukChun** [comment]
Thanks for the great question. Let me clarify each field by the first row
model (vsrn_full) / ranking (3)/ score (0.57) / cid (158306) / iid (581929) / annotation (3) / shortcoming 1 (1) / shortcoming 2 (2)

- cid and iid are the id of the given caption and the image, respectively. You can check ids from the official json `captions_val2014.json`
- model / ranking / score: It is the retrieval ranking and the corresponding score of the given iid/cid pair (in this case, 581929 and 158306). For example, here the VSRN model shows 0.57 similarity score for the given iid and cid. I don't think the ranking information is useful, but it is only used for the filtering (top-5 retrieved items)
- annotation: 1 -- 100% yes, 2 -- partially yes, 3 -- partially no, 4 -- 100% no
- shortcoming 1 is the annotation for why the given image-caption pairs are **partially** yes or no. There are 4 options as below. shortcoming 2 is only activated when shortcoming 1 is "it describes the main objects/concepts in the image, but in a wrong way"; there are 10 different options for which concept is incorrect. shortcoming 1 and shortcoming 2 are only collected for the first round because I found that the difference between methods is neglectable. Please check the below example for details.

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/4919315/216806964-6eee5239-949c-4b3f-8656-93e23f640e88.png">

**Comment by SanghyukChun** [comment]
Oh, I missed the metric question. I chose mAP@R instead of nDCG (or nDCG@R) in these reasons
- mAP@R is already a familiar metric in image retrieval benchmarks. (check this paper: https://arxiv.org/abs/2003.08505)
- nDCG needs more hyperparameters to set the "relevance score" for each 4-level annotation (what should be the relevance score for partially yes and partially no? Different hyperparameter selections could lead to different conclusions; I would like to avoid the such situation)
- The human annotations are not 100% clean, but they could be somewhat noisy. For example, there could be "partially no" annotations for the 100% NO case.

I think both mAP@R and nDCG are good design choices, but especially for the second reason, I'd prefer mAP@R in this dataset.

**Comment by shivangibithel** [comment]
Thank you so much for these informative insights.

**Comment by shivangibithel** [comment]
Hi @SanghyukChun 

I have a doubt while using the dataset, Most methods in the literature, use MSCOCO for Test-to-test retrieval, where they concatenate 5 captions together to form a single caption aligned to an image. 
So, MS-COCO 5K for Image to-text: 5K images as query and 5K captions in the retrieval set.

Here you mentioned the subsampling of the queries so now in Image to Text, 5K images for Query and the gallery set is 25,000 captions. So how is the dataset compatible with COCO 5K R@K directly because the gallery set is same but used in a different way ?

**Comment by SanghyukChun** [comment]
No that is not true.
MS-COCO 5K for image-to-text uses 5K images as the query set and 25K captions in the retrieval set.
As far as I know, there is no work that uses the concatenated caption as the retrieval gallery set.
Every method tested in my paper (e.g., Table 4) uses the same protocol in terms of the choice of the query set and the gallery set.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming my answer solves the question.
